name: myfitness
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  # Add any other Firebase services you want, e.g., firebase_auth, firebase_storage, etc.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/running.png
    - assets/outdoor running.jpg
    - assets/indoor cycling.jpg
    - assets/outdoor cycling.jpg
    - assets/rope skipping.jpg
    - assets/outdoor walking.jpg
    - assets/gym.png
    - assets/barbell.jpg
    - assets/dumbbell.jpg
    - assets/kettlebell.jpg
    - assets/smith.jpg
    - assets/profile.jpg
    - assets/running.jpg
    - assets/logo.png
    - assets/weights.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900
